name: UI API Hybrid Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install --with-deps

      - name: Run tests
        env:
          BASE_URL: https://practice.expandtesting.com
          LOGIN_URL: https://practice.expandtesting.com/login
          USERNAME: practice
          PASSWORD: practice
          HEADLESS: true
        run: |
          pytest
